Enhance:AdvancedSearch
yojo-art/cherrypick pull request #285
Opened 2024-08-06 13:49 UTC by penginn-net

## What

高度な検索の挙動変更
タブ分離(フロントエンド)
## Why

Close #273

## Additional info (optional)

## Checklist
- [ ] Read the [contribution guide](https://github.com/kokonect-link/cherrypick/blob/develop/CONTRIBUTING.md)
- [x] Test working in a local environment
- [x] (If needed) Update CHANGELOG_CHERRYPICK.md
- [ ] (If possible) Add tests

2024-08-06 14:05 UTC, kozakura913 requested changes

2024-08-06 15:47 UTC, kozakura913 requested changes

2024-08-07 03:07 UTC, jj1guj requested changes

2024-08-07 03:07 UTC, jj1guj commented on packages/backend/src/server/api/endpoints/admin/recreate-index.ts
> +
余分な空行入ってる気がする

2024-08-07 03:07 UTC, jj1guj commented on packages/backend/src/server/api/endpoints/notes/advanced-search.ts
> +
余分な空行入ってる気がする

2024-08-08 07:17 UTC, kozakura913 commented
ユーザー選択でリモートユーザー選択した時はホスト指定が該当サーバーになるけど後から変えられる
自分自身かローカルユーザーを指定してもローカルから検索に切り替わらない

ユーザー指定検索はそのユーザーが居るサーバーから検索した方が軽そう

2024-08-10 19:46 UTC, kozakura913 approved these changes

2024-08-11 19:18 UTC, jj1guj approved these changes
LGTM :+1:

2024-08-11 19:28 UTC, merged