Feat: indexableに対応
yojo-art/cherrypick pull request #449
Opened 2024-09-16 09:57 UTC by penginn-net

## What

検索許可の明示
toot:indexableに対応
検索仕様はmastodon準拠

## Why

Resolve #347 

## Additional info (optional)

つかれた

アカウント削除されたとかのunindex以外確認済み
## Checklist
- [x] [コントリビューションガイド](https://github.com/yojo-art/cherrypick/blob/develop/CONTRIBUTING.md)を読みました( Read the [contribution guide](https://github.com/yojo-art/cherrypick/blob/develop/CONTRIBUTING.md))
- [x] ローカル環境で動作しました(Test working in a local environment)
- [x] (必要なら)CHANGELOG_YOJO.mdの更新((If needed) Update CHANGELOG_YOJO.md)
- [x] (必要なら)テストの追加((If possible) Add tests)

2024-09-20 13:15 UTC, kozakura913 requested changes

2024-09-20 13:15 UTC, kozakura913 commented on locales/ja-JP.yml
> +makeIndexableDescription: "オフにすると、あなたのノートが検索で表示にくくなります。\nRenote 返信 投票 お気に入り クリップ リアクション\nされている場合は相手に表示されます。\nリモートのサーバーも対応している必要があります。"
mastodonと同じ機能だし同じ表記の方がわかりやすそう。リモートの挙動は制御できない事を明示してほしい

2024-09-20 13:15 UTC, kozakura913 commented on packages/backend/src/core/AdvancedSearchService.ts
> +		for (const note of notes) {
mapの方が意図がわかりやすそう

2024-09-21 03:19 UTC, kozakura913 commented on packages/frontend/src/pages/settings/privacy.vue
> +	<MkSwitch v-model="isIndexable" @update:modelValue="save()">
yojo-art機能ラベル欲しい

2024-09-22 16:16 UTC, kozakura913 commented
テストを動く状態にする必要がある

2024-09-24 06:11 UTC, kozakura913 commented on packages/backend/test/e2e/search-notes.ts
> +	test('indexable', async() => {
indexableのテスト細分化しないと見づらい

2024-09-24 11:39 UTC, kozakura913 requested changes

2024-09-24 11:39 UTC, kozakura913 commented on packages/backend/src/server/api/endpoints/notes/favorites/create.ts
> +			await	this.advancedSearchService.indexFavorite(id, {
謎タブ

2024-09-24 11:43 UTC, kozakura913 commented on CHANGELOG_YOJO.md
> +- Feat: mastodonのindexableに対応
インデント文字が混在してるから他の所に合わせて統一して

2024-09-24 11:44 UTC, kozakura913 commented on packages/backend/src/core/AdvancedSearchService.ts
> +				analyzer: 'sudachi_analyzer' },
開きが改行して閉じが改行してないのは違和感ある

2024-09-24 20:33 UTC, kozakura913 approved these changes

2024-09-28 07:43 UTC, kozakura913 commented
このPRでやると複雑化するし別PRに分割してほしい

2024-09-28 08:42 UTC, jj1guj approved these changes
LGTM

2024-09-29 08:23 UTC, kozakura913 commented
通常検索のindexableのテスト無い？

2024-10-01 14:11 UTC, kozakura913 commented on packages/backend/src/core/AdvancedSearchService.ts
>  				res = await this.opensearch.search(OpenSearchOption);
初回と2回目以降で違うコードで検索してると事故の原因になりそう

2024-10-15 12:49 UTC, merged